#!/usr/bin/env bash
# installs and makes nginx serve a page containing 'Hello World!'
apt-get update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
REDIR_STR="\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sed -i "47i $REDIR_STR" /etc/nginx/sites-available/default
service nginx start
