#!/usr/bin/env bash
# installs and makes nginx serve a page containing 'Hello World!'
apt-get update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html

ERROR_404_BLOCK="\terror_page 404 /custom_404.html;\n\t\n"
echo -e "Ceci n'est pas une page" > "/var/www/html/custom_404.html"

REDIR_STR="\\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
# sed -i "47i $REDIR_STR" /etc/nginx/sites-available/default

WHOLE_STR="$REDIR_STR\n$ERROR_404_BLOCK"

sed -i "47i $WHOLE_STR" /etc/nginx/sites-available/default

service nginx reload
