#!/usr/bin/env bash
# Installs, configures, and starts the server
# apt-get -y update
# apt-get -y install nginx
# ufw allow 'Nginx HTTP'
# mkdir -p /var/www/html /var/www/error
# chmod -R 755 /var/www
# echo 'Hello World!' > /var/www/html/index.html
# echo -e "Ceci n\x27est pas une page" > /var/www/error/404.html
# # the server's configuration
# SERVER_CONFIG=\
# "server {
# 	listen 80 default_server;
# 	listen [::]:80 default_server;
# 	root /var/www/html;
# 	index index.html index.htm index.nginx-debian.html;
# 	server_name _;
# 	location / {
# 		try_files \$uri \$uri/ =404;
# 	}
# 	if (\$request_filename ~ redirect_me){
# 		rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
# 	}
# 	error_page 404 /404.html;
# 	location = /404.html {
# 		root /var/www/error/;
# 		internal;
# 	}
#     add_header X-Served-By $HOSTNAME;
# }"
# bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"
# if [ "$(pgrep -c nginx)" -le 0 ]; then
# 	service nginx start
# else
# 	service nginx restart
# fi
#!/usr/bin/env bash
# Configure server with: Nginx, custom 404, custom 301 redirect to google
# Add to HTTP header

ADD301_REDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}\n"
ADD404_NOTFOUND="error_page 404 /custom_404.html;\n\\tlocation = /custom_404.html {\n\t\t root /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
PATTERN="#error_page 404 /404.html;"
ADD_HEADER="\\\tadd_header X-Served-By $HOSTNAME;"

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start

echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html

# melissax.online/redirect_me redirects to google.com (add to line 30)
sudo sed -i "30i $ADD301_REDIRECT" /etc/nginx/sites-available/default

# Any page that errors shows this new custom_404.html page (uncomment and replace code)
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "s@$PATTERN@$ADD404_NOTFOUND@" /etc/nginx/sites-available/default

# Header is updated (add_header to file)
sudo sed -i "27i $ADD_HEADER" /etc/nginx/sites-available/default

sudo service nginx restart
