#!/usr/bin/env bash
# Runs infinite loop and displays messages while taking into account the signal
# sent to the process
delete_pid_file_and_exit()
{
    rm -f /var/run/myscript.pid
    exit
}

trap "echo 'Y U no love me?!'" SIGINT # ctrl+c functionality overriden
trap "echo 'I hate the kill command'; delete_pid_file_and_exit" SIGTERM 
trap "echo 'I hate the kill command'; delete_pid_file_and_exit" SIGQUIT


echo $$ >> /var/run/myscript.pid
while true; do
    echo 'To infinity and beyond'
    sleep 2
done
