#!/usr/bin/env bash
# displays hours and minutes from 0 through 12 hours
hour=0
min=1
while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    while [ $min -le 59 ]; do
        echo $min
        ((++min))
    done
    min=1
    ((++hour))
done
