#!/usr/bin/env bash
# prints information about a file
file="school"
if [ -e $file ]; then # exists
    echo "school file exists"
    if [ ! -s $file ]; then # empty
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi
    if [ -f $file ]; then # regular file
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
